/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "basic.h"


void
calculadora_1(char *host, int n1, int n2)
{
	CLIENT *clnt;
	int  *result_1;
	// int suma_1_n1;
	// int suma_1_n2;
	int  *result_2;
	// int producto_1_n1;
	// int producto_1_n2;
	int  *result_3;
	// int resta_1_n1;
	// int resta_1_n2;
	int  *result_4;
	// int division_1_n1;
	// int division_1_n2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, BASIC_CALC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = suma_1(n1, n2, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = producto_1(n1, n2, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = resta_1(n1, n2, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = division_1(n1, n2, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int n1, n2;
	char operator;
	char input[10];

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];


	int correct_input = 1;

	while (correct_input==1){
		printf("¿Qué operación desea realizar? (Formato: num operador num)\n");
		fgets(input, 10, stdin);

		//Compruebo 
		if (3 != sscanf(input, "%d %c %d", &n1, &operator, &n2)) {
			printf("Formato invalido. \n");
		} else if(operator != '+' && operator != '-' && operator != 'x' && operator != '/'){
			printf("Operador %c invalido. Operadores válidos: \n", operator);
			printf("+ para sumar\n");
			printf("- para restar\n");
			printf("x para multiplicar\n");
			printf("/ para dividir\n");
		} else 
			correct_input = 0;
			
	}	
	 
	calculadora_1 (host, n1, n2);
exit (0);
}
