/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "basic.h"


void
calculadora_1(char *host, int n1, int n2, char operator)
{
	CLIENT *clnt;
	calc_res  *result_1;
	// int suma_1_n1;
	// int suma_1_n2;

	// int producto_1_n1;
	// int producto_1_n2;

	// int resta_1_n1;
	// int resta_1_n2;

	// int division_1_n1;
	// int division_1_n2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, BASIC_CALC, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (operator)
	{
	case '+':
		result_1 = suma_1(n1, n2, clnt);
		if (result_1 == (calc_res *)NULL){
			clnt_perror(clnt, "call failed");
		}
		break;
	case '-':
		result_1 = resta_1(n1, n2, clnt);
		if (result_1 == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	case '*':
		result_1 = producto_1(n1, n2, clnt);
		if (result_1 == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	case '/':
		result_1 = division_1(n1, n2, clnt);
		if (result_1 == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	}

	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int n1, n2;
	char operator;
	char input[30];

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int correct_input = 1, cont_reading = 0;

	while (cont_reading==0)
	{
		cont_reading = 0;
		printf("¿Qué operación desea realizar? (Formato: num operador num)\n");
		printf("\t+ para sumar\n");
		printf("\t- para restar\n");
		printf("\t* para multiplicar\n");
		printf("\t/ para dividir\n");
		printf("Pulse s para salir.\n");
		fgets(input, 30, stdin);


		// Compruebo si quiere teminar:
		if(strlen(input) == 2 && strcmp(input, "s\n")==0 ){
			cont_reading = 1;
		} else 
		//Compruebo la operacion introducida.
		if (3 != sscanf(input, "%d %c %d", &n1, &operator, & n2)) {
				printf("Formato invalido. \n");
		}	
		else if (operator!= '+' && operator!= '-' && operator!= '*' && operator!= '/')
		{
			printf("Operador %c invalido. \n", operator);
		} else
			calculadora_1 (host, n1, n2, operator);

		printf("---------------------------------------------------------------------------\n");
	}
	

	
exit (0);
}
