/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "basic.h"

calc_res *
suma_1_svc(int n1, int n2,  struct svc_req *rqstp)
{
	static calc_res result;

	result.calc_res_u.result=n1*n2;

    printf("Multiplicando... %d * %d = %d\n\n", n1, n2, result.calc_res_u.result);


	return &result;
}

calc_res *
producto_1_svc(int n1, int n2,  struct svc_req *rqstp)
{
	static calc_res  result;

	result.calc_res_u.result=n1*n2;

    printf("Multiplicando... %d * %d = %d\n\n", n1, n2, result.calc_res_u.result);
	return &result;
}

calc_res *
resta_1_svc(int n1, int n2,  struct svc_req *rqstp)
{
	static calc_res  result;

	result.calc_res_u.result=n1-n2;

    printf("Restando... %d - %d = %d\n\n", n1, n2, result.calc_res_u.result);

	return &result;
}

calc_res *
division_1_svc(int n1, int n2,  struct svc_req *rqstp)
{
	static calc_res  result;

	result.calc_res_u.result=n1/n2;

    printf("Dividiendo... %d / %d = %d\n\n", n1, n2, result.calc_res_u.result);

	return &result;
}
