/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
suma_1_svc(int n1, int n2,  struct svc_req *rqstp)
{
	static int  result;

    result=n1+n2;

    printf("%d + %d = %d\n\n", n1, n2, result);

    return &result;
}
