/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host, int n1, int n2)
{
    CLIENT *clnt;
    int  *result_1;
    // int suma_1_n1;
    // int suma_1_n2;

#ifndef    DEBUG
    clnt = clnt_create (host, CALCULADORA, SUM_CALC, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif    /* DEBUG */

    result_1 = suma_1(n1, n2, clnt);
    if (result_1 == (int *) NULL) {
        clnt_perror (clnt, "call failed");
    }
#ifndef    DEBUG
    clnt_destroy (clnt);
#endif     /* DEBUG */
}


int
main (int argc, char *argv[])
{
    char *host;
    int numero_1, numero_2;

    if (argc < 4) {
        printf ("usage: %s server_host numero_1 numero_2\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    numero_1 = atoi(argv[2]);
    numero_2 = atoi(argv[3]);
    calculadora_1 (host, numero_1, numero_2);
    exit (0);
}