/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

calc_res *
suma_1(double n1, double n2,  CLIENT *clnt)
{
	suma_1_argument arg;
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, suma, (xdrproc_t) xdr_suma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
producto_1(double n1, double n2,  CLIENT *clnt)
{
	producto_1_argument arg;
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, producto, (xdrproc_t) xdr_producto_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
resta_1(double n1, double n2,  CLIENT *clnt)
{
	resta_1_argument arg;
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, resta, (xdrproc_t) xdr_resta_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
division_1(double n1, double n2,  CLIENT *clnt)
{
	division_1_argument arg;
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, division, (xdrproc_t) xdr_division_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
raiz_1(double n1, double n2,  CLIENT *clnt)
{
	raiz_1_argument arg;
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, raiz, (xdrproc_t) xdr_raiz_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
potencia_1(double n1, double n2,  CLIENT *clnt)
{
	potencia_1_argument arg;
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, potencia, (xdrproc_t) xdr_potencia_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
